Name:           ros-melodic-dynamixel-workbench-controllers
Version:        1.0.0
Release:        0%{?dist}
Summary:        ROS dynamixel_workbench_controllers package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://wiki.ros.org/dynamixel_workbench_controllers
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-dynamixel-workbench-msgs
Requires:       ros-melodic-dynamixel-workbench-toolbox
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-dynamixel-workbench-msgs
BuildRequires:  ros-melodic-dynamixel-workbench-toolbox
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs

%description
This package contains examples of applying the 'dynamixel_workbench_toolbox'
library developed on the basis of dynamixel_sdk to various operating modes of
Dynamixel.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Jul 20 2018 Pyo <pyo@robotis.com> - 1.0.0-0
- Autogenerated by Bloom

* Mon Jun 04 2018 Pyo <pyo@robotis.com> - 0.3.1-0
- Autogenerated by Bloom

* Mon Jun 04 2018 Pyo <pyo@robotis.com> - 0.3.0-0
- Autogenerated by Bloom

